jobs:
  include:
  - stage: go-test
    language: go
    sudo: false
    go:
    - 1.11.x
    os:
    - linux
    script:
    - env GO111MODULE=on go get github.com/mjibson/esc
    - env GO111MODULE=on go generate
    - env GO111MODULE=on go build
    - env GO111MODULE=on go test ./...
  - stage: jshint
    language: node_js
    os:
    - linux
    script:
    - npm i -g jshint
    - cd static/js && jshint
  - stage: dockerhub push
    if: tag IS NOT present
    language: ruby
    services:
    - docker
    script:
    - docker build -t minetesttools/mapserver:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push minetesttools/mapserver
  - stage: dockerhub push tag
    if: tag IS present
    language: ruby
    services:
    - docker
    script:
    - docker build -t minetesttools/mapserver:latest .
    - docker tag minetesttools/mapserver:latest minetesttools/mapserver:$TRAVIS_TAG
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push minetesttools/mapserver

env:
  global:
  - secure: AH7d5fhIWuQlmTTZ72niDV+AHTGoBhjXxh+zSJcfqny8JctvfFNuwjc+IuQjlwdsEob6VEEVGfWNIdOwNVpkuJRuH9s5LVnBovbcORc2emOUnK8ecWdLUj9frApSHWxbHAaKCYfGOWdFnFhWWhhB4VzWTy8NkfcpqqQgxFtT5unD7GXuOjLOOdfHpFhjkji1GkWGOblBeLI6MIoVIaPWtFh+zKI/tzD5cW7ISzaMLY0rVg8jyxyZcCpsrEJNQzJ4gjyME0Cx+aEGyxaH71qwlf7O2IaZMlUGY2+BzVVND2Cd1//vx7mJrrNccODgqGy4pQhXQNTyOa6+9JqOAxhY/ykjIlzurXmVmEMEidtxrsR5bar6eLfh8EPAFS8pf3q+Awt4uS/rX9sstrDveSBZ+bZMnkHfSVjNsylb9E0QsyU2KuEMX+x0ezn0fc5jOGBFaeUu+LV+7ZPg6yzQDNGztMHjPzih7kbt01fwGlYAvG0FIMPX+EygCnIiP3OozI0VRO1WGI40RJjt/ow60J8TqC0O6npysgMzqSeCJuoL475sKkCmKhcPbYQf603hKw1YYPbpL8aNSrvCuCF3J+UJiBtlAXPzmMaqEFp1bxJZspicILFEl5CIwy/U7C+Fr8rL4C1BHQvSQ+nEWGz6vng6OE+YFKNvRWwwla3p1UToUKQ=
  - secure: h9VCO6x/P2RzxkLRHbAuj9/wfVZiTuZJ7dmO1lXrbnY623X/3Svi4KQPvz0tmxt4OxTFKTy/8CfxkcX3hXwTgpKytTgYhWnPXUL4Vjnp/gHfIu0Z7ae5TYP3Cpefs+DqPgVpljkY+jd/WZQZnEsJN+tAygztOhArVZVwgJEBOWqU33nMRFfwkcsu5GjFicBJ/0vlX7xaVTUNGEkNRadMe8XG/LvR00zy9pimpO8mDO+yyQf8D7OAttY2gzaMxe27OU4YGngcxtU8A8+4Pvk8r8IhNtlyiBY57P0m3zugvZiB0k73hAypH2RA6/5EcJ3+bcERD+xwT9HqOZda7rntdKVUVwR9Re9Ggfj3k0/fFFvsHzqanwNBAL+wuQXrojbzaIPF+8BugFXiiM7UoqoVeUz/cCf+MiXccvRkM9+erDE8fZYXSp9ePx46D/cK93TOdoF/2nD+I9FwRcgxDs60KEpj6V1xq8uEOS8VGUqDvS4vmqkebO2i133JhudG/746oyraWOR9SgNK0Cxsk1yKe0wXIi9AwOFybEkNbJzALD4zm08UBkvHNBqSp8yaV0Uj7wX4ZOk8zEYaNWsglVai99pOIzPxgP1H5ylwlWBNPmud188xxAxU0RgnuqbKiG508hJoYTlU+u6cPPirC6haEPxhfa/goyLVp0K8cSWj2es=
