matrix:
  include:
    - stage: test
      language: go
      sudo: false
      go:
       - 1.11.x
      os:
       - linux
      script:
       - env GO111MODULE=on go get github.com/mjibson/esc
       - env GO111MODULE=on go generate
       - env GO111MODULE=on go build
       - env GO111MODULE=on go test ./...

    - stage: dockerhub push
      language: ruby
      services:
        - docker
      script:
        - docker build -t buckaroobanzay/mapserver:latest .
        - docker tag buckaroobanzay/mapserver:latest buckaroobanzay/mapserver:$TRAVIS_TAG
