name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # only on tags or the master branch
      - name: Docker Login
        if: success() && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # only on tags
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run tests
      - name: Run tests
        run: |
          docker build . --progress plain --no-cache --target run-test

      # only on the master branch
      - name: Build and push latest docker image
        if: success() && github.ref == 'refs/heads/master'
        run: |
          docker build . -t minetestmapserver/mapserver:latest
          docker push minetestmapserver/mapserver:latest
