name: docker

on:
  push:
    branches-ignore:
     - 'renovate/*'
     - 'dependabot/*'
    tags:
     - '*'
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@master

    - name: docker publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: minetestmapserver/mapserver
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: true
