name: push-latest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: erray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

